name: A test workflow trigger through the github api

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test job
        run: |
          sleep 20
          echo "Job finished succesfully!"
